
  export default {
    "dev": {
  "platform-dev-fullstack": {
    "userAPIUrl": "https://w76yg34zg6.execute-api.ap-southeast-1.amazonaws.com/dev/",
    "festSeasonsTableName": "platform-dev-fullstack-platformDevFestSeasons7C8124F8-1HUA3304VM16G",
    "gameQuestTableName": "platform-dev-fullstack-platformDevGameQuestE6BB7FF8-1QMVHPW5INQ8W",
    "logTableName": "platform-dev-fullstack-platformDevLog5F4D181B-WXHRI4U0Z7EW",
    "festTeamsTableName": "platform-dev-fullstack-platformDevFestTeams532D2482-1N7HRCFEYJPOH",
    "festTeamMembersTableName": "platform-dev-fullstack-platformDevFestTeamMembers81EF098B-TKBSVHRG4PX",
    "festUserRewardsTableName": "platform-dev-fullstack-platformDevFestUserRewards5640CAB0-1M4JZ783VLJHG",
    "openChestTableName": "platform-dev-fullstack-platformDevOpenChest812531C3-1LAC9PNKZFREF",
    "festLeaderboardTableName": "platform-dev-fullstack-platformDevFestLeaderboard9C0B7B4D-1U7MWYR40UMFL",
    "gameChestTableName": "platform-dev-fullstack-platformDevGameChest59AE672C-1S1TA0AVLTJNX",
    "referralCodeTableName": "platform-dev-fullstack-platformDevReferralCodeB1B52C42-1HZZN5RII8CXK",
    "userPoolClientId": "hjjeapem4t8djppqucrcep43c",
    "festUserTeamStakingsTableName": "platform-dev-fullstack-platformDevFestUserTeamStakingsB3D54471-102QLUUIU3TJZ",
    "referralConnectionCreatedAtGsi": "CreatedAtGsi",
    "referralConnectionTableName": "platform-dev-fullstack-platformDevReferralConnection54229816-WUJV5JFOSAEU",
    "festTeamTopScoresScoreIndexGsi": "ScoreIndexGsi",
    "contentCounterTableName": "platform-dev-fullstack-platformDevContentCounter57ABA55E-1UOT2IRZZ2521",
    "nftOwnershipTableName": "platform-dev-fullstack-platformDevNftOwnership920A55A4-M4L8J3H1TPA3",
    "gameAssetTableName": "platform-dev-fullstack-platformDevGameAsset0D9E545D-P6YDSR4MHY1K",
    "nftCollectionTableName": "platform-dev-fullstack-platformDevNftCollectionCE24B49D-A35CWZL099U7",
    "referralConnectionUserIdGsi": "UserIdGsi",
    "env": "{\"STAGE\":\"dev\",\"PROJECT_NAME\":\"platform\",\"REGION\":\"ap-southeast-1\",\"API_HOST\":\"rest.suzume.io\",\"ALLOWED_ORIGINS\":\"localhost:7654,localhost:7546,localhost:5173,suzume.io,tun1.suzume-api.xyz,tun2.suzume-api.xyz,tun3.suzume-api.xyz,tun4.suzume-api.xyz\",\"JWT_SECRET\":\"Saij743RiFi8WIs4cD3RyCCXaGjaivieN\",\"BY_PASS_VALUE\":\"Gg930HtEt0cD\",\"BOT_SECRET_TOKEN\":\"secret\",\"NFT_API_SECRET\":\"token\",\"NFT_S3_BUCKET\":\"bucket\",\"UPLOAD_S3_ACCESS_KEY\":\"UPLOAD_S3_ACCESS_KEY\",\"UPLOAD_S3_SECRET\":\"UPLOAD_S3_SECRET\",\"UPLOAD_REGION\":\"UPLOAD_REGION\",\"TELEGRAM_CHANNEL_SECRET\":\"secret\",\"USER_POOL_ID\":\"ap-southeast-1_nhdyGM3Aq\",\"USER_POOL_CLIENT_ID\":\"hjjeapem4t8djppqucrcep43c\",\"LOG_TABLE_NAME\":\"platform-dev-fullstack-platformDevLog5F4D181B-WXHRI4U0Z7EW\",\"REFERRAL_CODE_TABLE_NAME\":\"platform-dev-fullstack-platformDevReferralCodeB1B52C42-1HZZN5RII8CXK\",\"REFERRAL_CONNECTION_TABLE_NAME\":\"platform-dev-fullstack-platformDevReferralConnection54229816-WUJV5JFOSAEU\",\"USER_ASSET_TABLE_NAME\":\"platform-dev-fullstack-platformDevUserAsset26265FCE-S69R801FMKVH\",\"USER_INBOX_TABLE_NAME\":\"platform-dev-fullstack-platformDevUserInboxBC71AE55-KW44PIQX7QN8\",\"GAME_ENTRY_TABLE_NAME\":\"platform-dev-fullstack-platformDevGameEntry210B920C-2SVKIBWMCPHR\",\"GAME_QUEST_TABLE_NAME\":\"platform-dev-fullstack-platformDevGameQuestE6BB7FF8-1QMVHPW5INQ8W\",\"OPEN_CHEST_TABLE_NAME\":\"platform-dev-fullstack-platformDevOpenChest812531C3-1LAC9PNKZFREF\",\"GAME_ASSET_TABLE_NAME\":\"platform-dev-fullstack-platformDevGameAsset0D9E545D-P6YDSR4MHY1K\",\"GAME_STATE_TABLE_NAME\":\"platform-dev-fullstack-platformDevGameState953EA121-XCX8TL6AAXQD\",\"GAME_COUNTER_TABLE_NAME\":\"platform-dev-fullstack-platformDevGameCounter14EE83B8-KBF4CPSAB22Q\",\"CONTENT_COUNTER_TABLE_NAME\":\"platform-dev-fullstack-platformDevContentCounter57ABA55E-1UOT2IRZZ2521\",\"GAME_NFT_OWNERSHIP_TABLE_NAME\":\"platform-dev-fullstack-platformDevNftOwnership920A55A4-M4L8J3H1TPA3\",\"GAME_NFT_COLLECTION_TABLE_NAME\":\"platform-dev-fullstack-platformDevNftCollectionCE24B49D-A35CWZL099U7\",\"GAME_CHEST_TABLE_NAME\":\"platform-dev-fullstack-platformDevGameChest59AE672C-1S1TA0AVLTJNX\",\"GAME_DESIGN_TABLE_NAME\":\"platform-dev-fullstack-platformDevGameDesignBC725D2E-VQ3LBA0GQ7XE\",\"FEST_SEASONS\":\"platform-dev-fullstack-platformDevFestSeasons7C8124F8-1HUA3304VM16G\",\"FEST_TEAMS\":\"platform-dev-fullstack-platformDevFestTeams532D2482-1N7HRCFEYJPOH\",\"FEST_TEAM_MEMBERS\":\"platform-dev-fullstack-platformDevFestTeamMembers81EF098B-TKBSVHRG4PX\",\"FEST_USER_TEAM_STAKINGS\":\"platform-dev-fullstack-platformDevFestUserTeamStakingsB3D54471-102QLUUIU3TJZ\",\"FEST_LEADERBOARD\":\"platform-dev-fullstack-platformDevFestLeaderboard9C0B7B4D-1U7MWYR40UMFL\",\"FEST_TEAM_TOP_SCORES\":\"platform-dev-fullstack-platformDevFestTeamTopScores1766D668-1TLRRDFIMP3XT\",\"FEST_TEAM_REWARDS\":\"platform-dev-fullstack-platformDevFestTeamRewardsF69185FE-1TC732ASIK8M\",\"FEST_USER_REWARDS\":\"platform-dev-fullstack-platformDevFestUserRewards5640CAB0-1M4JZ783VLJHG\",\"RELEASE_VERSION\":\"a54c1b06dce7db5a718e9cd5d6928f0b4cfb4f2472c1486a8f03a262ca4fec7a\"}",
    "festTeamRewardsTableName": "platform-dev-fullstack-platformDevFestTeamRewardsF69185FE-1TC732ASIK8M",
    "gameStateTableName": "platform-dev-fullstack-platformDevGameState953EA121-XCX8TL6AAXQD",
    "gameCounterTableName": "platform-dev-fullstack-platformDevGameCounter14EE83B8-KBF4CPSAB22Q",
    "userAssetTableName": "platform-dev-fullstack-platformDevUserAsset26265FCE-S69R801FMKVH",
    "festTeamTopScoresTableName": "platform-dev-fullstack-platformDevFestTeamTopScores1766D668-1TLRRDFIMP3XT",
    "userInboxTableName": "platform-dev-fullstack-platformDevUserInboxBC71AE55-KW44PIQX7QN8",
    "gameDesignTableName": "platform-dev-fullstack-platformDevGameDesignBC725D2E-VQ3LBA0GQ7XE",
    "platformDevUserGatewayEndpoint412A7BE7": "https://w76yg34zg6.execute-api.ap-southeast-1.amazonaws.com/dev/",
    "gameEntryTableName": "platform-dev-fullstack-platformDevGameEntry210B920C-2SVKIBWMCPHR",
    "userPoolId": "ap-southeast-1_nhdyGM3Aq"
  }
},
    "pro": {
  "platform-pro-fullstack": {
    "platformProUserGatewayEndpointBCA0C41F": "https://bx4jht8yn6.execute-api.ap-southeast-1.amazonaws.com/pro/",
    "userAPIUrl": "https://bx4jht8yn6.execute-api.ap-southeast-1.amazonaws.com/pro/",
    "festSeasonsTableName": "platform-pro-fullstack-platformProFestSeasons9CCF2261-1FU2NRVXRUFGI",
    "gameQuestTableName": "platform-pro-fullstack-platformProGameQuest9BF46197-HSGNFW7IQMPU",
    "logTableName": "platform-pro-fullstack-platformProLog9C730DDE-VCXVIJI6BAQQ",
    "festTeamsTableName": "platform-pro-fullstack-platformProFestTeams9A8C8BDB-177KTHGQAHZUF",
    "festTeamMembersTableName": "platform-pro-fullstack-platformProFestTeamMembers65AB68B2-1C4903ZDNWEF",
    "festUserRewardsTableName": "platform-pro-fullstack-platformProFestUserRewardsD603B3CF-XH2L3VV5EFI4",
    "openChestTableName": "platform-pro-fullstack-platformProOpenChestF105DB2B-LW1YKZUJUB1M",
    "festLeaderboardTableName": "platform-pro-fullstack-platformProFestLeaderboard8B0DA43C-Z1HDAIQE5LO3",
    "gameChestTableName": "platform-pro-fullstack-platformProGameChest0DF3D953-1HWX1PKHBYGIO",
    "referralCodeTableName": "platform-pro-fullstack-platformProReferralCode49ECA384-EXJ2Y7WJ47XE",
    "userPoolClientId": "b3itsa38818f0nb0eljqrr5eu",
    "festUserTeamStakingsTableName": "platform-pro-fullstack-platformProFestUserTeamStakingsE08B4DF8-6LE6PGSLL5M0",
    "referralConnectionCreatedAtGsi": "CreatedAtGsi",
    "referralConnectionTableName": "platform-pro-fullstack-platformProReferralConnectionAB10239A-JW7ADQEG3POT",
    "festTeamTopScoresScoreIndexGsi": "ScoreIndexGsi",
    "contentCounterTableName": "platform-pro-fullstack-platformProContentCounterE1A29185-16IUN4J8W7IIT",
    "nftOwnershipTableName": "platform-pro-fullstack-platformProNftOwnership04372151-1LISM1Z98THE2",
    "gameAssetTableName": "platform-pro-fullstack-platformProGameAsset79973101-30SSD42JPI3T",
    "nftCollectionTableName": "platform-pro-fullstack-platformProNftCollectionAC4A3BD2-TNU2414G544N",
    "referralConnectionUserIdGsi": "UserIdGsi",
    "env": "{\"STAGE\":\"pro\",\"PROJECT_NAME\":\"platform\",\"REGION\":\"ap-southeast-1\",\"API_HOST\":\"rest.suzume.io\",\"ALLOWED_ORIGINS\":\"localhost:7654,localhost:7546,localhost:5173,suzume.io,tun1.suzume-api.xyz,tun2.suzume-api.xyz,tun3.suzume-api.xyz,tun4.suzume-api.xyz\",\"JWT_SECRET\":\"Saij743RiFi8WIs4cD3RyCCXaGjaivieN\",\"BY_PASS_VALUE\":\"Gg930HtEt0cD\",\"BOT_SECRET_TOKEN\":\"secret\",\"NFT_API_SECRET\":\"token\",\"NFT_S3_BUCKET\":\"bucket\",\"UPLOAD_S3_ACCESS_KEY\":\"UPLOAD_S3_ACCESS_KEY\",\"UPLOAD_S3_SECRET\":\"UPLOAD_S3_SECRET\",\"UPLOAD_REGION\":\"UPLOAD_REGION\",\"TELEGRAM_CHANNEL_SECRET\":\"secret\",\"USER_POOL_ID\":\"ap-southeast-1_Q7yWnjSbj\",\"USER_POOL_CLIENT_ID\":\"b3itsa38818f0nb0eljqrr5eu\",\"LOG_TABLE_NAME\":\"platform-pro-fullstack-platformProLog9C730DDE-VCXVIJI6BAQQ\",\"REFERRAL_CODE_TABLE_NAME\":\"platform-pro-fullstack-platformProReferralCode49ECA384-EXJ2Y7WJ47XE\",\"REFERRAL_CONNECTION_TABLE_NAME\":\"platform-pro-fullstack-platformProReferralConnectionAB10239A-JW7ADQEG3POT\",\"USER_ASSET_TABLE_NAME\":\"platform-pro-fullstack-platformProUserAssetC5DF2A16-15F111CNHKZ27\",\"USER_INBOX_TABLE_NAME\":\"platform-pro-fullstack-platformProUserInboxBE95AE01-1NE4LSEXEH1NO\",\"GAME_ENTRY_TABLE_NAME\":\"platform-pro-fullstack-platformProGameEntry17253241-RG0IG1YTWCC3\",\"GAME_QUEST_TABLE_NAME\":\"platform-pro-fullstack-platformProGameQuest9BF46197-HSGNFW7IQMPU\",\"OPEN_CHEST_TABLE_NAME\":\"platform-pro-fullstack-platformProOpenChestF105DB2B-LW1YKZUJUB1M\",\"GAME_ASSET_TABLE_NAME\":\"platform-pro-fullstack-platformProGameAsset79973101-30SSD42JPI3T\",\"GAME_COUNTER_TABLE_NAME\":\"platform-pro-fullstack-platformProGameCounter698E9A4C-PKCH7E6CG54O\",\"CONTENT_COUNTER_TABLE_NAME\":\"platform-pro-fullstack-platformProContentCounterE1A29185-16IUN4J8W7IIT\",\"GAME_NFT_OWNERSHIP_TABLE_NAME\":\"platform-pro-fullstack-platformProNftOwnership04372151-1LISM1Z98THE2\",\"GAME_NFT_COLLECTION_TABLE_NAME\":\"platform-pro-fullstack-platformProNftCollectionAC4A3BD2-TNU2414G544N\",\"GAME_CHEST_TABLE_NAME\":\"platform-pro-fullstack-platformProGameChest0DF3D953-1HWX1PKHBYGIO\",\"GAME_DESIGN_TABLE_NAME\":\"platform-pro-fullstack-platformProGameDesignFB8EFB40-1JTV0MPSNXE9T\",\"FEST_SEASONS\":\"platform-pro-fullstack-platformProFestSeasons9CCF2261-1FU2NRVXRUFGI\",\"FEST_TEAMS\":\"platform-pro-fullstack-platformProFestTeams9A8C8BDB-177KTHGQAHZUF\",\"FEST_TEAM_MEMBERS\":\"platform-pro-fullstack-platformProFestTeamMembers65AB68B2-1C4903ZDNWEF\",\"FEST_USER_TEAM_STAKINGS\":\"platform-pro-fullstack-platformProFestUserTeamStakingsE08B4DF8-6LE6PGSLL5M0\",\"FEST_LEADERBOARD\":\"platform-pro-fullstack-platformProFestLeaderboard8B0DA43C-Z1HDAIQE5LO3\",\"FEST_TEAM_TOP_SCORES\":\"platform-pro-fullstack-platformProFestTeamTopScoresCC854129-1JXQHR4U9KHC3\",\"FEST_TEAM_REWARDS\":\"platform-pro-fullstack-platformProFestTeamRewards5283C80B-2S4KP8OZ0HSH\",\"FEST_USER_REWARDS\":\"platform-pro-fullstack-platformProFestUserRewardsD603B3CF-XH2L3VV5EFI4\",\"RELEASE_VERSION\":\"7d0438cf9921eee81ce01b165f68fa24057a49246be36c038d1da65e2d21be11\"}",
    "festTeamRewardsTableName": "platform-pro-fullstack-platformProFestTeamRewards5283C80B-2S4KP8OZ0HSH",
    "gameCounterTableName": "platform-pro-fullstack-platformProGameCounter698E9A4C-PKCH7E6CG54O",
    "userAssetTableName": "platform-pro-fullstack-platformProUserAssetC5DF2A16-15F111CNHKZ27",
    "festTeamTopScoresTableName": "platform-pro-fullstack-platformProFestTeamTopScoresCC854129-1JXQHR4U9KHC3",
    "userInboxTableName": "platform-pro-fullstack-platformProUserInboxBE95AE01-1NE4LSEXEH1NO",
    "gameDesignTableName": "platform-pro-fullstack-platformProGameDesignFB8EFB40-1JTV0MPSNXE9T",
    "gameEntryTableName": "platform-pro-fullstack-platformProGameEntry17253241-RG0IG1YTWCC3",
    "userPoolId": "ap-southeast-1_Q7yWnjSbj"
  }
}
  }